### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by Ahmetf1** [andreasBihlmaier/pysdf#15]
rosrun pysdf sdf2urdf.py plane.sdf plane.urdf
Traceback (most recent call last):
  File "/home/afa/catkin_ws/src/pysdf/scripts/sdf2urdf.py", line 6, in <module>
    import pysdf
  File "/home/afa/catkin_ws/devel/lib/python3/dist-packages/pysdf/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 1, in <module>
  File "/home/afa/catkin_ws/src/pysdf/src/pysdf/parse.py", line 11, in <module>
    from tf.transformations import *
  File "/opt/ros/noetic/lib/python3/dist-packages/tf/__init__.py", line 30, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/opt/ros/noetic/lib/python3/dist-packages/tf2_ros/__init__.py", line 38, in <module>
    from tf2_py import *
  File "/opt/ros/noetic/lib/python3/dist-packages/tf2_py/__init__.py", line 38, in <module>
    from ._tf2 import *
ImportError: dynamic module does not define init function (init_tf2)

**Comment by Ahmetf1** [comment]
I couldn't find the problem. Can someone help?

**Comment by engineerkong** [comment]
Hi Ahmetf1, how you solved this problem?
