### ISSUE TITLE
sdf2urdf doesn't work

### ISSUE THREAD

**Issue by pavelgivoy** [andreasBihlmaier/pysdf#19]
Hi! I'm trying to run sdf2urdf, but I'm getting the error:

`Traceback (most recent call last):`
`  File "/home/user/zephyr_ws/src/pysdf/scripts/sdf2urdf.py", line 6, in <module>`
`    import pysdf`
`  File "/home/user/zephyr_ws/devel/lib/python3/dist-packages/pysdf/__init__.py", line 34, in <module>`
`    exec(__fh.read())`
`  File "<string>", line 1, in <module>`
`ModuleNotFoundError: No module named 'parse'`

The problem occurs either with or without using ROS. Do you have any idea to fix it, please?

**Comment by wbthomason** [comment]
You can fix this by prefixing the problematic imports with `pysdf.` or simply `.`. The issue arises because of Python 3 no longer allowing implicit relative imports.

**Comment by wbthomason** [comment]
See also #16, #17
