### ISSUE TITLE
pysdf error

### ISSUE THREAD

**Issue by EnesKcuk** [andreasBihlmaier/pysdf#20]
Hi I am trying to covert frrom sdf file to urdf
and getting this error

eyup@eyup-FLEXDEX304:~/catkin_ws4/src/iq_sim/models/iris_base$ rosrun pysdf sdf2urdf.py model.sdf model.urdf
Traceback (most recent call last):
  File "/home/eyup/catkin_ws4/src/pysdf/scripts/sdf2urdf.py", line 31, in <module>
    main()
  File "/home/eyup/catkin_ws4/src/pysdf/scripts/sdf2urdf.py", line 17, in main
    sdf = pysdf.SDF(file=args.sdf)
TypeError: _init_(): incompatible constructor arguments. The following argument types are supported:
    1. pysdf.SDF(verts: numpy.ndarray[numpy.float32[m, 3], flags.c_contiguous], faces: numpy.ndarray[numpy.uint32[m, 3], flags.c_contiguous], robust: bool = True, copy: bool = True)

Invoked with: kwargs: file='model.sdf'

any idea to fix it?

**Comment by li-yongyao** [comment]
I also have this issue...

**Comment by ATflux** [comment]
In sdf2urdf.py script change `#!/usr/bin/env python3` to `#!/usr/bin/env python`. It should work.
